#ifndef __CIR_TX_SUN20IW2_H_
#define __CIR_TX_SUN20IW2_H_

#if defined(CONFIG_ARCH_RISCV_C906)
#define SUNXI_IRQ_IRTX	66
#elif defined(CONFIG_ARCH_DSP)
#define SUNXI_IRQ_IRTX	51
#else
#define SUNXI_IRQ_IRTX	50
#endif

#define SUNXI_IRTX_PBASE	0x40046400
#define IRADC_PIN		GPIO_PA13
#define IR_MUXSEL		5
#define IR_DRVSEL		2

#define SUNXI_IRTX_RESET_TYPE	HAL_SUNXI_RESET
#define SUNXI_IRTX_CLK_TYPE	HAL_SUNXI_CCU
#define SUNXI_RST_IRTX		RST_IRTX
#define SUNXI_CLK_BUS_IRTX	CLK_IRTX
#define SUNXI_CLK_MODULE_IRTX	CLK_IR_TX

#endif /* __CIR_TX_SUN20IW2_H_ */
