obj-y += xbtc_uart.o

CFLAGS        += -I include/drivers/
CFLAGS        += -I include/freertos/
CFLAGS        += -I include
CFLAGS        += -I drivers/drv/wireless/xradio/os/include
CFLAGS        += -I components/common/aw/xradio/cmd/
CFLAGS        += -I components/common/aw/xradio/include/
CFLAGS        += -I components/common/aw/xradio/bt_uart/
CFLAGS        += -I drivers/drv/wireless/xradio/
CFLAGS        += -I drivers/drv/bluetooth/include/lib
CFLAGS        += -I drivers/drv/bluetooth/include/driver
