obj-$(CONFIG_TESTCASE_AUDIO_MIC_CAPTURE) += tt-mic_capture.o
obj-$(CONFIG_TESTCASE_AUDIO_SPEAKER_PLAYBACK) += tt-speaker_playback.o
obj-$(CONFIG_TESTCASE_AUDIO_PLAYBACK_AND_CAPTURE) += tt-playback_and_capture.o
obj-$(CONFIG_TESTCASE_AUDIO_PLAYBACK_OPEN_CLOSE) += tt-playback_open_close.o

