/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __PLATFORM_GPIO_H__
#define __PLATFORM_GPIO_H__

#ifdef __cplusplus
extern "C" {
#endif

#define GPIO_MAX_BANK PL_BASE
#define BANK_BOUNDARY PL_BASE
#define SUNXI_GPIO_PBASE 0x02000000
#define SUNXI_GPIO_R_PBASE 0x07022000
#define SUNXI_GPIO_RES_SIZE 0x07FF

/* sunxi gpio irq*/
#if defined(CONFIG_CORE_DSP0) /* DSP */
#include <interrupt.h>
#define SUNXI_IRQ_GPIOB (RINTC_IRQ_MASK | 40)
#define SUNXI_IRQ_GPIOC (RINTC_IRQ_MASK | 42)
#define SUNXI_IRQ_GPIOD (RINTC_IRQ_MASK | 44)
#define SUNXI_IRQ_GPIOE (RINTC_IRQ_MASK | 46)
#define SUNXI_IRQ_GPIOF (RINTC_IRQ_MASK | 48)
#define SUNXI_IRQ_GPIOG (RINTC_IRQ_MASK | 50)
#define SUNXI_IRQ_R_GPIOL (RINTC_IRQ_MASK | 2)
#endif /* CONFIG_CORE_DSP0 */

#if defined(CONFIG_ARCH_RISCV) /* E906 */
#include <interrupt.h>
#define SUNXI_IRQ_GPIOB (MAKE_IRQn(98, 6))
#define SUNXI_IRQ_GPIOC (MAKE_IRQn(98, 8))
#define SUNXI_IRQ_GPIOD (MAKE_IRQn(99, 2))
#define SUNXI_IRQ_GPIOE (MAKE_IRQn(99, 4))
#define SUNXI_IRQ_GPIOF (MAKE_IRQn(99, 6))
#define SUNXI_IRQ_GPIOG (MAKE_IRQn(99, 8))
#define SUNXI_IRQ_GPIOH (MAKE_IRQn(100, 2))
#define SUNXI_IRQ_GPIOI (MAKE_IRQn(100, 4))
#define SUNXI_IRQ_GPIOJ (MAKE_IRQn(100, 6))
#define SUNXI_IRQ_GPIOK (MAKE_IRQn(107, 5))
#define SUNXI_IRQ_R_GPIOL (MAKE_IRQn(63, 0))
#define SUNXI_IRQ_R_GPIOM (MAKE_IRQn(65, 0))
#endif

typedef enum
{
    GPIO_PB0 = GPIOB(0),
    GPIO_PB1 = GPIOB(1),
    GPIO_PB2 = GPIOB(2),
    GPIO_PB3 = GPIOB(3),
    GPIO_PB4 = GPIOB(4),
    GPIO_PB5 = GPIOB(5),
    GPIO_PB6 = GPIOB(6),
    GPIO_PB7 = GPIOB(7),
    GPIO_PB8 = GPIOB(8),

    GPIO_PC0 = GPIOC(0),
    GPIO_PC1 = GPIOC(1),
    GPIO_PC2 = GPIOC(2),
    GPIO_PC3 = GPIOC(3),
    GPIO_PC4 = GPIOC(4),
    GPIO_PC5 = GPIOC(5),
    GPIO_PC6 = GPIOC(6),
    GPIO_PC7 = GPIOC(7),

    GPIO_PD0 = GPIOD(0),
    GPIO_PD1 = GPIOD(1),
    GPIO_PD2 = GPIOD(2),
    GPIO_PD3 = GPIOD(3),
    GPIO_PD4 = GPIOD(4),
    GPIO_PD5 = GPIOD(5),
    GPIO_PD6 = GPIOD(6),
    GPIO_PD7 = GPIOD(7),
    GPIO_PD8 = GPIOD(8),
    GPIO_PD9 = GPIOD(9),
    GPIO_PD10 = GPIOD(10),
    GPIO_PD11 = GPIOD(11),
    GPIO_PD12 = GPIOD(12),
    GPIO_PD13 = GPIOD(13),
    GPIO_PD14 = GPIOD(14),
    GPIO_PD15 = GPIOD(15),
    GPIO_PD16 = GPIOD(16),
    GPIO_PD17 = GPIOD(17),
    GPIO_PD18 = GPIOD(18),
    GPIO_PD19 = GPIOD(19),
    GPIO_PD20 = GPIOD(20),
    GPIO_PD21 = GPIOD(21),
    GPIO_PD22 = GPIOD(22),

    GPIO_PE0 = GPIOE(0),
    GPIO_PE1 = GPIOE(1),
    GPIO_PE2 = GPIOE(2),
    GPIO_PE3 = GPIOE(3),
    GPIO_PE4 = GPIOE(4),
    GPIO_PE5 = GPIOE(5),
    GPIO_PE6 = GPIOE(6),
    GPIO_PE7 = GPIOE(7),
    GPIO_PE8 = GPIOE(8),
    GPIO_PE9 = GPIOE(9),
    GPIO_PE10 = GPIOE(10),
    GPIO_PE11 = GPIOE(11),
    GPIO_PE12 = GPIOE(12),
    GPIO_PE13 = GPIOE(13),
    GPIO_PE14 = GPIOE(14),
    GPIO_PE15 = GPIOE(15),
    GPIO_PE16 = GPIOE(16),
    GPIO_PE17 = GPIOE(17),

    GPIO_PF0 = GPIOF(0),
    GPIO_PF1 = GPIOF(1),
    GPIO_PF2 = GPIOF(2),
    GPIO_PF3 = GPIOF(3),
    GPIO_PF4 = GPIOF(4),
    GPIO_PF5 = GPIOF(5),
    GPIO_PF6 = GPIOF(6),

    GPIO_PG0 = GPIOG(0),
    GPIO_PG1 = GPIOG(1),
    GPIO_PG2 = GPIOG(2),
    GPIO_PG3 = GPIOG(3),
    GPIO_PG4 = GPIOG(4),
    GPIO_PG5 = GPIOG(5),
    GPIO_PG6 = GPIOG(6),
    GPIO_PG7 = GPIOG(7),
    GPIO_PG8 = GPIOG(8),
    GPIO_PG9 = GPIOG(9),
    GPIO_PG10 = GPIOG(10),
    GPIO_PG11 = GPIOG(11),
    GPIO_PG12 = GPIOG(12),
    GPIO_PG13 = GPIOG(13),
    GPIO_PG14 = GPIOG(14),
    GPIO_PG15 = GPIOG(15),

    GPIO_PH0 = GPIOH(0),
    GPIO_PH1 = GPIOH(1),
    GPIO_PH2 = GPIOH(2),
    GPIO_PH3 = GPIOH(3),
    GPIO_PH4 = GPIOH(4),
    GPIO_PH5 = GPIOH(5),
    GPIO_PH6 = GPIOH(6),
    GPIO_PH7 = GPIOH(7),
    GPIO_PH8 = GPIOH(8),
    GPIO_PH9 = GPIOH(9),
    GPIO_PH10 = GPIOH(10),
    GPIO_PH11 = GPIOH(11),
    GPIO_PH12 = GPIOH(12),
    GPIO_PH13 = GPIOH(13),
    GPIO_PH14 = GPIOH(14),
    GPIO_PH15 = GPIOH(15),

    GPIO_PI0 = GPIOI(0),
    GPIO_PI1 = GPIOI(1),
    GPIO_PI2 = GPIOI(2),
    GPIO_PI3 = GPIOI(3),
    GPIO_PI4 = GPIOI(4),
    GPIO_PI5 = GPIOI(5),
    GPIO_PI6 = GPIOI(6),
    GPIO_PI7 = GPIOI(7),
    GPIO_PI8 = GPIOI(8),
    GPIO_PI9 = GPIOI(9),
    GPIO_PI10 = GPIOI(10),
    GPIO_PI11 = GPIOI(11),
    GPIO_PI12 = GPIOI(12),
    GPIO_PI13 = GPIOI(13),
    GPIO_PI14 = GPIOI(14),
    GPIO_PI15 = GPIOI(15),
    GPIO_PI16 = GPIOI(16),

    GPIO_PJ0 = GPIOJ(0),
    GPIO_PJ1 = GPIOJ(1),
    GPIO_PJ2 = GPIOJ(2),
    GPIO_PJ3 = GPIOJ(3),
    GPIO_PJ4 = GPIOJ(4),
    GPIO_PJ5 = GPIOJ(5),
    GPIO_PJ6 = GPIOJ(6),
    GPIO_PJ7 = GPIOJ(7),
    GPIO_PJ8 = GPIOJ(8),
    GPIO_PJ9 = GPIOJ(9),
    GPIO_PJ10 = GPIOJ(10),
    GPIO_PJ11 = GPIOJ(11),
    GPIO_PJ12 = GPIOJ(12),
    GPIO_PJ13 = GPIOJ(13),
    GPIO_PJ14 = GPIOJ(14),
    GPIO_PJ15 = GPIOJ(15),
    GPIO_PJ16 = GPIOJ(16),
    GPIO_PJ17 = GPIOJ(17),
    GPIO_PJ18 = GPIOJ(18),
    GPIO_PJ19 = GPIOJ(19),
    GPIO_PJ20 = GPIOJ(20),
    GPIO_PJ21 = GPIOJ(21),
    GPIO_PJ22 = GPIOJ(22),
    GPIO_PJ23 = GPIOJ(23),

    GPIO_PK0 = GPIOK(0),
    GPIO_PK1 = GPIOK(1),
    GPIO_PK2 = GPIOK(2),
    GPIO_PK3 = GPIOK(3),
    GPIO_PK4 = GPIOK(4),
    GPIO_PK5 = GPIOK(5),
    GPIO_PK6 = GPIOK(6),
    GPIO_PK7 = GPIOK(7),
    GPIO_PK8 = GPIOK(8),
    GPIO_PK9 = GPIOK(9),
    GPIO_PK10 = GPIOK(10),
    GPIO_PK11 = GPIOK(11),
    GPIO_PK12 = GPIOK(12),
    GPIO_PK13 = GPIOK(13),
    GPIO_PK14 = GPIOK(14),
    GPIO_PK15 = GPIOK(15),
    GPIO_PK16 = GPIOK(16),
    GPIO_PK17 = GPIOK(17),
    GPIO_PK18 = GPIOK(18),
    GPIO_PK19 = GPIOK(19),
    GPIO_PK20 = GPIOK(20),
    GPIO_PK21 = GPIOK(21),
    GPIO_PK22 = GPIOK(22),
    GPIO_PK23 = GPIOK(23),

    GPIO_PL0 = GPIOL(0),
    GPIO_PL1 = GPIOL(1),
    GPIO_PL2 = GPIOL(2),
    GPIO_PL3 = GPIOL(3),
    GPIO_PL4 = GPIOL(4),
    GPIO_PL5 = GPIOL(5),
    GPIO_PL6 = GPIOL(6),
    GPIO_PL7 = GPIOL(7),
    GPIO_PL8 = GPIOL(8),
    GPIO_PL9 = GPIOL(9),
    GPIO_PL10 = GPIOL(10),
    GPIO_PL11 = GPIOL(11),
    GPIO_PL12 = GPIOL(12),
    GPIO_PL13 = GPIOL(13),

    GPIO_PM0 = GPIOM(0),
    GPIO_PM1 = GPIOM(1),
    GPIO_PM2 = GPIOM(2),
    GPIO_PM3 = GPIOM(3),
    GPIO_PM4 = GPIOM(4),
    GPIO_PM5 = GPIOM(5),


    /* To aviod compile warnings. */
    GPIO_MAX = GPIOO(31),

} gpio_pin_t;

#ifdef __cplusplus
}
#endif
#endif /* __PLATFORM_GPIO_H__ */
