/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY¡¯S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS¡¯SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY¡¯S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __LPUART_SUN20IW2_H__
#define __LPUART_SUN20IW2_H__

#define SUNXI_CLK_LPUART0	CLK_LPUART0
#define SUNXI_CLK_LPUART0_WKUP	CLK_LPUART0_WKUP
#define SUNXI_RST_LPUART0 RST_LPUART0

#define SUNXI_CLK_LPUART1 CLK_LPUART1
#define SUNXI_CLK_LPUART1_WKUP	CLK_LPUART1_WKUP
#define SUNXI_RST_LPUART1 RST_LPUART1

#if defined(CONFIG_ARCH_RISCV_C906)
#define SUNXI_IRQ_LPUART0                (55)
#define SUNXI_IRQ_LPUART1                (56)
#elif defined(CONFIG_ARCH_DSP)
#define SUNXI_IRQ_LPUART0                (40)
#define SUNXI_IRQ_LPUART1                (41)
#else
#define SUNXI_IRQ_LPUART0                (39)
#define SUNXI_IRQ_LPUART1                (40)
#endif

/* base register infomation */
#define SUNXI_LPUART0_BASE                           (0x4004A800)
#define SUNXI_LPUART1_BASE                           (0x4004AC00)
#define SUNXI_CCMU_AON_BASE			     (0x4004C400)

#define LPUART_FIFO_SIZE                            (64)
#define LPUART0_GPIO_FUNCTION                        (2)
#define LPUART1_GPIO_FUNCTION                        (2)

#define LPUART0_TX    GPIOB(0)
#define LPUART0_RX    GPIOB(1)

#define LPUART1_TX    GPIOB(14)
#define LPUART1_RX    GPIOB(15)


#endif /*__LPUART_SUN20IW2_P1__  */
