BT_DRV_AMP_DIRS += $(shell find $(BT_DRV_BASE)/driver/interface/$(BT_INTERFACE_SELECT) -type d)


CFLAGS += -I drivers/drv/bluetooth/driver/interface/$(BT_INTERFACE_SELECT)
CFLAGS += -I components/aw/bluetooth/xradio/pm
