obj-y += cpu.o
obj-y += main.o
obj-y += platops.o
obj-y += pm_manager.o
obj-y += pm_rpc.o
obj-y += pm_wakesrc.o
obj-y += pm_systeminit.o

CFLAGS += -I components/common/aw/pm/plat_riscv/
CFLAGS += -I components/common/aw/pm/plat_riscv/include

