obj-y +=$(OPUS_TEST_DIR)/test/opus_test.o
obj-y +=$(OPUS_TEST_DIR)/opus_decode.o
obj-y +=$(OPUS_TEST_DIR)/opus_encode.o

RTOPUS_INCLUDE_DIR := components/aw/multimedia/include/

CFLAGS += -I $(RTOPUS_INCLUDE_DIR)
CFLAGS += -I compoments/aw/multimedia/opus_test/
CFLAGS += -I components/thirdparty/console/

