obj-y += cmd_hci_log.o

CFLAGS += -I components/common/thirdparty/bluetooth/tools/btsnoop/include
CFLAGS += -I components/common/thirdparty/bluetooth/tools/hcidump/include/hcidump_xr
CFLAGS += -I components/common/aw/xradio/cmd
CFLAGS += -I components/common/aw/xradio/include
