obj-y += sunxi-input.o

CFLAGS += -I $(BASE)/include/drivers/
CFLAGS += -I $(BASE)/include/arch/mach
CFLAGS += -I $(BASE)/include/freertos/

obj-$(CONFIG_DRIVERS_KEYBOARD) += keyboard/
obj-$(CONFIG_DRIVERS_TOUCHSCREEN) += tp/
