obj-$(CONFIG_COMPONENTS_TFM_TEST) += tfm_test.o
obj-$(CONFIG_COMPONENTS_TFM_DEBUG) += tfm_debug.o
#obj-y += lib/s_veneers.o

CFLAGS += -I components/aw/tfm/include/
CFLAGS += -I arch/arm/armv8m/include/cmsis/
