obj-$(CONFIG_COMPONENTS_TCPIP) += tcpip/
obj-$(CONFIG_COMPONENTS_LOOPIF_TEST) += loopif_test/
obj-$(CONFIG_COMPONENTS_WIFI) += wifi/
obj-$(CONFIG_COMPONENTS_WLAN_CSFC) += wlan_csfc/
obj-$(CONFIG_COMPONENTS_WLAN_MAC) += wlan_mac/
obj-$(CONFIG_COMPONENTS_WLAN_COUNTRY_CODE) += wlan_country_code/
obj-y += service/
