obj-y += src/hal_atomic.o
obj-y += src/hal_cache.o
obj-y += src/hal_interrupt.o
obj-y += src/hal_mem.o
obj-y += src/hal_mutex.o
obj-y += src/hal_queue.o
obj-y += src/hal_sem.o
obj-y += src/hal_thread.o
obj-y += src/hal_timer.o
obj-y += src/hal_time.o
obj-y += src/hal_waitqueue.o
obj-y += src/hal_workqueue.o
obj-y += src/hal_cfg.o
obj-y += src/hal_cpu.o
obj-y += src/hal_event.o

CFLAGS += -I $(BASE)/drivers/osal/include
CFLAGS += -I $(BASE)/drivers/rtos-hal/include/osal
