ifeq ($(CONFIG_DRIVERS_BLUETOOTH_XRADIO), y)

obj-$(CONFIG_COMPONENTS_BLUEDROID) += bluedroid/
obj-$(CONFIG_COMPONENTS_ZEPHYR) += zephyr/
obj-$(CONFIG_AW_COMPONENT_ETF) += etf/
obj-y += common/

endif

obj-$(CONFIG_AW_COMPONENT_BLUEDROID_CTRL) += controller/
obj-$(CONFIG_AW_COMPONENT_XBTC_UART) += xbtc_uart/
