obj-$(CONFIG_COMPONENTS_SMARTCONFIG) += smartconfig/
obj-$(CONFIG_COMPONENTS_BLINK) += blink/
obj-$(CONFIG_COMPONENTS_SOFT_AP_CONFIG) += soft_ap_config/
obj-$(CONFIG_COMPONENTS_VOICE_PRINT) += voice_print/
