/*
 * Generated by erpcgen 1.8.1 on Fri Jun 11 19:08:28 2021.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_demo_h_)
#define _demo_h_

#include "sunxi_amp.h"

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

// Enumerators data types declarations
typedef enum lockErrors_t
{
    lErrorOk_c = 0,
    lErrorOutofMemory_c = 1,
    lErrorMaxError_c = 2
} lockErrors_t;

// Aliases data types declarations
typedef struct binary_t binary_t;

// Structures/unions data types declarations
struct binary_t
{
    uint8_t *data;
    uint32_t dataLength;
};


#endif // ERPC_TYPE_DEFINITIONS

#if defined(__cplusplus)
extern "C" {
#endif

//! @name DEMO
//@{
binary_t *demo1(const binary_t *txInput);

lockErrors_t demo2(const binary_t *txInput, binary_t *txOutput);

lockErrors_t demo3(const binary_t *txInput, int8_t txOutput[64], int32_t *size);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _demo_h_
