/*
 * Generated by erpcgen 1.8.1 on Fri Jun 11 19:08:28 2021.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_demo_service_h_)
#define _demo_service_h_


typedef struct
{
    sunxi_amp_func_table demo1;
    sunxi_amp_func_table demo2;
    sunxi_amp_func_table demo3;
} RPCHandler_DEMO_t;

#endif // _demo_service_h_
