obj-$(CONFIG_TESTCASE_BTON) += tt-btcommon.o
obj-$(CONFIG_TESTCASE_BTON) += tt-onbt.o
obj-$(CONFIG_TESTCASE_BTOFF) += tt-offbt.o
obj-$(CONFIG_TESTCASE_BTSCAN) += tt-scanbt.o

CFLAGS += -I components/common/aw/xradio/include
CFLAGS += -I components/common/aw/wireless/btmanager/src
CFLAGS += -I components/common/thirdparty/bluetooth/zephyr/include
CFLAGS += -I components/common/thirdparty/bluetooth/zephyr/include/ble
