$(BUILD_DIR)/projects/$(RTOS_TARGET_PROJECT_PATH)/freertos.lds: MODULE_NAME="Linker"
LINKER_SCRIPTS += $(BUILD_DIR)/projects/$(RTOS_TARGET_PROJECT_PATH)/freertos.lds

LINKER_SCRIPT=$(LINKER_SCRIPTS)

ifeq ($(CONFIG_ARCH_SUN20IW2P1)_$(CONFIG_XIP), y_y)
LINKER_SCRIPTS_CFLAGS += -DRTOS_TARGET_PROJECT_PATH=$(RTOS_PROJECT_NAME)
endif
