CFLAGS += -std=c99 -Wextra -Werror -mno-coproc -mno-l32r-flix

obj-$(CONFIG_PORT_XCC_XTENSA) += XCC/Xtensa/port.o
obj-$(CONFIG_PORT_XCC_XTENSA) += XCC/Xtensa/portasm.o
obj-$(CONFIG_PORT_XCC_XTENSA) += XCC/Xtensa/portclib.o
obj-$(CONFIG_PORT_XCC_XTENSA) += XCC/Xtensa/xtensa_init.o
obj-$(CONFIG_PORT_XCC_XTENSA) += XCC/Xtensa/xtensa_context.o
obj-$(CONFIG_PORT_XCC_XTENSA) += XCC/Xtensa/xtensa_intr.o
obj-$(CONFIG_PORT_XCC_XTENSA) += XCC/Xtensa/xtensa_intr_asm.o
obj-$(CONFIG_PORT_XCC_XTENSA) += XCC/Xtensa/xtensa_overlay_os_hook.o
obj-$(CONFIG_PORT_XCC_XTENSA) += XCC/Xtensa/xtensa_vectors.o
obj-$(CONFIG_PORT_XCC_XTENSA) += XCC/Xtensa/nmi-handler.o

obj-$(CONFIG_MEMMANG_HEAP_1) += MemMang/heap_1.o
obj-$(CONFIG_MEMMANG_HEAP_2) += MemMang/heap_2.o
obj-$(CONFIG_MEMMANG_HEAP_3) += MemMang/heap_3.o
obj-$(CONFIG_MEMMANG_HEAP_4) += MemMang/heap_4.o
obj-$(CONFIG_MEMMANG_HEAP_5) += MemMang/heap_5.o
obj-$(CONFIG_MEMMANG_HEAP_MULTIPLE) += MemMang/heap_multiple.o
