obj-$(CONFIG_MULTI_CONSOLE) += console.o
obj-$(CONFIG_MULTI_CONSOLE) += porting.o
obj-$(CONFIG_MULTI_CONSOLE) += shell.o
obj-$(CONFIG_MULTI_CONSOLE) += doexit.o
obj-$(CONFIG_MULTI_CONSOLE) += null_console.o
obj-$(CONFIG_MULTI_CONSOLE) += multi_console.o
obj-$(CONFIG_UART_MULTI_CONSOLE) += uart_console.o
obj-$(CONFIG_RPMSG_MULTI_CONSOLE) += rpmsg_console/

CFLAGS += -I components/common/thirdparty/openamp/include
