obj-$(CONFIG_COMPONENTS_RPBUF_DEMO) += rpbuf_demo.o
obj-$(CONFIG_COMPONENTS_RPBUF_DEMO) += rpbuf_test.o md5.o

CFLAGS += -I components/common/aw/rpbuf/include
CFLAGS += -I components/common/thirdparty/openamp/include
CFLAGS += -I components/common/thirdparty/md5
