obj-y += newlibc/
obj-y += devfs/
obj-y += blkpart/
obj-y += secure_storage/
obj-y += healthd/
obj-y += smartlink/
obj-y += bluetooth/
obj-y += multimedia/

obj-$(CONFIG_KASAN) += kasan/
obj-$(CONFIG_COMPONENTS_MEMLEAK) += memleak/
obj-$(CONFIG_COMPONENTS_WATCHPOINT) += watchpoint/
obj-$(CONFIG_COMPONENTS_RAMFS) += ramfs/
obj-$(CONFIG_COMPONENTS_OSTEST) += ostest/
obj-$(CONFIG_COMPONENTS_TFM) += tfm/
obj-$(CONFIG_HPSRAM_INIT_IN_OS) += hpsram/
obj-$(CONFIG_COMPONENTS_CAMERA_PREVIEW) += camera_preview/
obj-$(CONFIG_COMPONENTS_WIRELESS_VIDEO) += wireless_video//
obj-$(CONFIG_COMPONENTS_PSTORE) += pstore/

