obj-$(CONFIG_KERNEL_FREERTOS) += FreeRTOS/portable/
obj-$(CONFIG_KERNEL_FREERTOS) += FreeRTOS/event_groups.o
obj-$(CONFIG_KERNEL_FREERTOS) += FreeRTOS/list.o
obj-$(CONFIG_KERNEL_FREERTOS) += FreeRTOS/queue.o
obj-$(CONFIG_KERNEL_FREERTOS) += FreeRTOS/stream_buffer.o
obj-$(CONFIG_KERNEL_FREERTOS) += FreeRTOS/tasks.o
obj-$(CONFIG_KERNEL_FREERTOS) += FreeRTOS/timers.o
obj-$(CONFIG_KERNEL_FREERTOS) += FreeRTOS/FreeRTOS_tick_config.o
