obj-$(CONFIG_DRIVERS_SPI_CAMERA) += spi_sensor/
obj-$(CONFIG_DRIVERS_SPI_CAMERA) += spi_camera.o

subdir-ccflags-y += -I drivers/rtos-hal/hal/source/spicamera/spi_camera
subdir-ccflags-y += -I drivers/rtos-hal/hal/source/spicamera/spi_camera/spi_sensor
subdir-ccflags-y += -I drivers/rtos-hal/include/hal/sdmmc/hal/
subdir-ccflags-y += -I drivers/rtos-hal/include/hal/sdmmc/osal/
