obj-$(CONFIG_DRIVERS_TOUCHSCREEN_TLSC6X) += tlsc6x/
obj-$(CONFIG_DRIVERS_TOUCHSCREEN_GT911) += gt911/
obj-$(CONFIG_DRIVERS_TOUCHSCREEN_CST226SE) += cst226se/

CFLAGS += -I include/drivers/
CFLAGS += -I include/arch/mach
CFLAGS += -I include/freertos/
