asflags-y += -Idrivers/rtos-hal/hal/source/sound/component/aw-alsa-utils

obj-$(CONFIG_COMPONENTS_AW_ALSA_UTILS) += common.o
obj-$(CONFIG_COMPONENTS_AW_ALSA_UTILS) += wav_parser.o
obj-$(CONFIG_COMPONENTS_AW_ALSA_UTILS) += card.o
obj-$(CONFIG_COMPONENTS_AW_ALSA_UTILS_APLAY) += aplay.o
obj-$(CONFIG_COMPONENTS_AW_ALSA_UTILS_ARECORD) += arecord.o
obj-$(CONFIG_COMPONENTS_AW_ALSA_UTILS_AMIXER) += amixer.o
obj-$(CONFIG_COMPONENTS_AW_ALSA_UTILS_ALOOP) += aloop.o
