obj-y += rtplayer_test.o

RTPLAYER_INCLUDE_DIR := components/aw/multimedia/include/

CFLAGS += -I $(RTPLAYER_INCLUDE_DIR)
CFLAGS += -I $(RTPLAYER_INCLUDE_DIR)/include/cedarx/xplayer/include/
CFLAGS += -I $(RTPLAYER_INCLUDE_DIR)/libcore/base/include/
CFLAGS += -I $(RTPLAYER_INCLUDE_DIR)/libcore/playback/include/
CFLAGS += -I $(RTPLAYER_INCLUDE_DIR)/libcore/parser/include/
CFLAGS += -I $(RTPLAYER_INCLUDE_DIR)/libcore/stream/include/
CFLAGS += -I $(RTPLAYER_INCLUDE_DIR)/Cdx2.0Plugin/include/
CFLAGS += -I components/thirdparty/console/
CFLAGS += -I components/common/aw/AudioSystem/include
CFLAGS += -D_POSIX_TIMERS


