obj-y += common/
obj-$(CONFIG_ARCH_SUN50IW11) += sun50iw11/
obj-$(CONFIG_ARCH_SUN8IW20) += sun8iw20/
obj-$(CONFIG_ARCH_SUN20IW2) += sun20iw2/
obj-$(CONFIG_ARCH_SUN55IW3) += sun55iw3/
obj-$(CONFIG_ARCH_SUN60IW1) += sun60iw1/
