obj-$(CONFIG_CSI_CAMERA) += csi.o
obj-$(CONFIG_CSI_CAMERA) += csi_reg/csi_reg.o
obj-$(CONFIG_CSI_CAMERA) += sensor/sensor_helper.o
obj-$(CONFIG_CSI_CAMERA_GC0308) += sensor/drv_gc0308.o
obj-$(CONFIG_CSI_CAMERA_GC0328c) += sensor/drv_gc0328c.o
obj-$(CONFIG_CSI_CAMERA_GC2145) += sensor/drv_gc2145.o
obj-$(CONFIG_CSI_CAMERA_OV7670) += sensor/ov7670/drv_ov7670.o
