obj-y += source/FreeRTOS_POSIX_clock.o
obj-y += source/FreeRTOS_POSIX_mqueue.o
obj-y += source/FreeRTOS_POSIX_pthread_barrier.o
obj-y += source/FreeRTOS_POSIX_pthread.o
obj-y += source/FreeRTOS_POSIX_pthread_cond.o
obj-y += source/FreeRTOS_POSIX_pthread_mutex.o
obj-y += source/FreeRTOS_POSIX_sched.o
obj-y += source/FreeRTOS_POSIX_semaphore.o
obj-y += source/FreeRTOS_POSIX_timer.o
obj-y += source/FreeRTOS_POSIX_unistd.o
obj-y += source/FreeRTOS_POSIX_utils.o

CFLAGS += -D_POSIX_MONOTONIC_CLOCK -D_POSIX_TIMERS
