#obj-y += ExampleCustomerWriter.o
obj-y += recorder_test.o

RTRECORDER_INCLUDE_DIR := components/aw/multimedia/include/

CFLAGS += -I $(RTRECORDER_INCLUDE_DIR)
CFLAGS += -I $(RTRECORDER_INCLUDE_DIR)/libcore/base/include/
CFLAGS += -I $(RTRECORDER_INCLUDE_DIR)/libcore/stream/include/
CFLAGS += -I $(RTRECORDER_INCLUDE_DIR)/libcore/record/include/
CFLAGS += -I $(RTRECORDER_INCLUDE_DIR)/libcore/writer/include/
CFLAGS += -I $(RTRECORDER_INCLUDE_DIR)/CdxEncPlugin/include/
CFLAGS += -I $(RTRECORDER_INCLUDE_DIR)/xrecoder/include/
CFLAGS += -I components/common/aw/pm/include/
CFLAGS += -I components/thirdparty/console/


