obj-$(CONFIG_DRIVERS_CSI) += hal_csi_jpeg.o
obj-$(CONFIG_CSI_CAMERA) += csi_camera/
obj-$(CONFIG_JPEG_ENCODER) += jpeg/

subdir-ccflags-y += -I drivers/rtos-hal/hal/source/csi/include/
subdir-ccflags-y += -I drivers/rtos-hal/hal/source/csi/
subdir-ccflags-y += -I drivers/rtos-hal/hal/source/csi/csi_camera/csi_reg/
subdir-ccflags-y += -I drivers/rtos-hal/hal/source/csi/utility/
subdir-ccflags-y += -I drivers/rtos-hal/hal/source/csi/jpeg/jpeg_reg/
subdir-ccflags-y += -I drivers/rtos-hal/hal/source/csi/jpeg/
subdir-ccflags-y += -I drivers/rtos-hal/include/hal/csi/
subdir-ccflags-y += -I drivers/rtos-hal/include/hal/sdmmc/hal/
subdir-ccflags-y += -I drivers/rtos-hal/include/hal/sdmmc/osal/
