        *build/RTOS_TARGET_PROJECT_PATH/components/thirdparty/console*.o (.text .text.* .rodata .rodata.*)
        *build/RTOS_TARGET_PROJECT_PATH/components/thirdparty/lfs*.o (.text .text.* .rodata .rodata.*)
	    *build/RTOS_TARGET_PROJECT_PATH/components/aw/ostest/hw_perf/base_perf.o (.text .text.* .rodata .rodata.*)
	    *build/RTOS_TARGET_PROJECT_PATH/components/aw/ostest/hw_perf/bus_perf.o (.text .text.* .rodata .rodata.*)
	    *build/RTOS_TARGET_PROJECT_PATH/components/aw/ostest/hw_perf/hexdump.o (.text .text.* .rodata .rodata.*)
	    *build/RTOS_TARGET_PROJECT_PATH/components/aw/ostest/hw_perf/mem_psram_perf.o (.text .text.* .rodata .rodata.*)
	    *build/RTOS_TARGET_PROJECT_PATH/components/aw/ostest/hw_perf/mem_sram_perf.o (.text .text.* .rodata .rodata.*)
	    *build/RTOS_TARGET_PROJECT_PATH/components/aw/ostest/hw_perf/mem_xip_perf.o (.text .text.* .rodata .rodata.*)
	    *build/RTOS_TARGET_PROJECT_PATH/components/aw/ostest/hw_perf/nop_inst.o (.text .text.* .rodata .rodata.*)
	    *build/RTOS_TARGET_PROJECT_PATH/components/aw/ostest/hw_perf/cache_penalty.o (.text .text.* .rodata .rodata.*)
	    *build/RTOS_TARGET_PROJECT_PATH/components/thirdparty/elmfat/src/ff.o (.text .text.* .rodata .rodata.*)
        *build/RTOS_TARGET_PROJECT_PATH/components/thirdparty/elmfat/src/ffsystem.o (.text .text.* .rodata .rodata.*)
        *build/RTOS_TARGET_PROJECT_PATH/components/thirdparty/elmfat/src/ffunicode.o (.text .text.* .rodata .rodata.*)
        *build/RTOS_TARGET_PROJECT_PATH/components/common/thirdparty/md5/md5.o (.text .text.* .rodata .rodata.*)
	    *build/RTOS_TARGET_PROJECT_PATH/components/common/thirdparty/coremark*.o (.text .text.* .rodata .rodata.*)
	    *build/RTOS_TARGET_PROJECT_PATH/components/common/thirdparty/env/env.o (.text .text.* .rodata .rodata.*)
	    *build/RTOS_TARGET_PROJECT_PATH/components/common/aw/iobox*.o (.text .text.* .rodata .rodata.*)
	    *build/RTOS_TARGET_PROJECT_PATH/components/common/aw/usb/gadget/adbd*.o (.text .text.* .rodata .rodata.*)
	    *build/RTOS_TARGET_PROJECT_PATH/components/common/aw/OpenMax*.o (.text .text.* .rodata .rodata.*)
	    *build/RTOS_TARGET_PROJECT_PATH/components/common/aw/amp/service*.o (.text .text.* .rodata .rodata.*)
        *build/RTOS_TARGET_PROJECT_PATH/components/aw/multimedia/rtplayer_test/rtplayer_test.o (.text .text.* .rodata .rodata.*)
        *build/RTOS_TARGET_PROJECT_PATH/drivers/hal/test/ce/test_ce.o (.text .text.* .rodata .rodata.*)
        *build/RTOS_TARGET_PROJECT_PATH/drivers/hal/test/dma/test_dma.o (.text .text.* .rodata .rodata.*)
        *build/RTOS_TARGET_PROJECT_PATH/drivers/hal/test/gpadc/test_gpadc.o (.text .text.* .rodata .rodata.*)
        *build/RTOS_TARGET_PROJECT_PATH/drivers/hal/test/usb/host/test_hci.o (.text .text.* .rodata .rodata.*)
        *build/RTOS_TARGET_PROJECT_PATH/drivers/hal/test/msgbox/test_msgbox.o (.text .text.* .rodata .rodata.*)
        *build/RTOS_TARGET_PROJECT_PATH/drivers/hal/test/pwm/test_pwm.o (.text .text.* .rodata .rodata.*)
        *build/RTOS_TARGET_PROJECT_PATH/drivers/hal/test/thermal/test_thermal.o (.text .text.* .rodata .rodata.*)
        *build/RTOS_TARGET_PROJECT_PATH/drivers/hal/test/rtc/test_rtc.o (.text .text.* .rodata .rodata.*)
        *build/RTOS_TARGET_PROJECT_PATH/drivers/hal/test/trng/test_trng.o (.text .text.* .rodata .rodata.*)

	    *libxrbtc.a: (.text .text.* .rodata .rodata.*)
	    *libxrbtc.o (.text .text.* .rodata .rodata.*)

        *libadecoder.a: (.text .text.* .rodata .rodata.*)
        *libarecoder.a: (.text .text.* .rodata .rodata.*)
        *libaw_mp3dec.a: (.text .text.* .rodata .rodata.*)
        *libaw_aacdec.a: (.text .text.* .rodata .rodata.*)
        *libaw_amrdec.a: (.text .text.* .rodata .rodata.*)
        *libaw_amrenc.a: (.text .text.* .rodata .rodata.*)
        *libaw_flacdec.a: (.text .text.* .rodata .rodata.*)
        *libaw_oggdec.a: (.text .text.* .rodata .rodata.*)
        *libaw_opuscodec.a: (.text .text.* .rodata .rodata.*)
        *libaw_wavdec.a: (.text .text.* .rodata .rodata.*)
        *libcdx_base.a: (.text .text.* .rodata .rodata.*)
        *libmuxer.a: (.text .text.* .rodata .rodata.*)
        *libparser.a: (.text .text.* .rodata .rodata.*)
        *libplayback.a: (.text .text.* .rodata .rodata.*)
        *librecord.a: (.text .text.* .rodata .rodata.*)
        *librtplayer.a: (.text .text.* .rodata .rodata.*)
        *libstream.a: (.text .text.* .rodata .rodata.*)
        *libxplayer.a: (.text .text.* .rodata .rodata.*)
        *libxrecorder.a: (.text .text.* .rodata .rodata.*)
        *libaudiosystem_c906.a: (.text .text.* .rodata .rodata.*)

        *libadecoder.o (.text .text.* .rodata .rodata.*)
        *libarecoder.o (.text .text.* .rodata .rodata.*)
        *libaw_mp3dec.o (.text .text.* .rodata .rodata.*)
        *libaw_aacdec.o (.text .text.* .rodata .rodata.*)
        *libaw_amrdec.o (.text .text.* .rodata .rodata.*)
        *libaw_amrenc.o (.text .text.* .rodata .rodata.*)
        *libaw_flacdec.o (.text .text.* .rodata .rodata.*)
        *libaw_oggdec.o (.text .text.* .rodata .rodata.*)
        *libaw_opuscodec.o (.text .text.* .rodata .rodata.*)
        *libaw_wavdec.o (.text .text.* .rodata .rodata.*)
        *libcdx_base.o (.text .text.* .rodata .rodata.*)
        *libmuxer.o (.text .text.* .rodata .rodata.*)
        *libparser.o (.text .text.* .rodata .rodata.*)
        *libplayback.o (.text .text.* .rodata .rodata.*)
        *librecord.o (.text .text.* .rodata .rodata.*)
        *librtplayer.o (.text .text.* .rodata .rodata.*)
        *libstream.o (.text .text.* .rodata .rodata.*)
        *libxplayer.o (.text .text.* .rodata .rodata.*)
        *libxrecorder.o (.text .text.* .rodata .rodata.*)
        *libaudiosystem_c906.o (.text .text.* .rodata .rodata.*)

#ifdef CONFIG_COMPONENTS_BTMANAGER
        *build/RTOS_TARGET_PROJECT_PATH/components/common/aw/wireless/btmanager*.o (.text .text.* .rodata .rodata.*)
#endif
#ifdef CONFIG_COMPONENTS_WIFIMANAGER
        *build/RTOS_TARGET_PROJECT_PATH/components/common/aw/wireless/wifimanager*.o (.text .text.* .rodata .rodata.*)
#endif
#ifdef CONFIG_COMPONENTS_WIRELSEE_COMMON
        *build/RTOS_TARGET_PROJECT_PATH/components/common/aw/wireless/common*.o (.text .text.* .rodata .rodata.*)
#endif
#ifdef CONFIG_DRIVERS_WIRELESS
#include "wlan.lds.S"
#endif
#if CONFIG_COMPONENT_BT || CONFIG_AW_COMPONENT_BLUEDROID_CTRL || CONFIG_AW_COMPONENT_ETF
#include "bt.lds.S"
#endif


#ifdef CONFIG_COMPONENTS_AW_TINY_ALSA_LIB
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-tiny-alsa-lib/control.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-tiny-alsa-lib/pcm.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-tiny-alsa-lib/pcm_config.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-tiny-alsa-lib/pcm_hw.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-tiny-alsa-lib/pcm_mmap.o (.text .text.* .rodata .rodata.*)
#endif /* CONFIG_COMPONENTS_AW_TINY_ALSA_LIB */

#ifdef CONFIG_COMPONENTS_AW_ALSA_LIB
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/control.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_asym.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_config.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_direct.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_dmix.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_dsnoop.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_extplug.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_file.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_generic.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_hw.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_linear.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_misc.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_mmap.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_multi.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_params.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_plug.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_plugin_generic.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_rate.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_rate_linear.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_route.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-lib/pcm_softvol.o (.text .text.* .rodata .rodata.*)
#endif /* CONFIG_COMPONENTS_AW_ALSA_LIB */

#ifdef CONFIG_COMPONENTS_AW_ALSA_UTILS
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-utils/arecord.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-utils/aplay.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-utils/amixer.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-utils/card.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-utils/common.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-utils/wav_parser.o (.text .text.* .rodata .rodata.*)

	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-utils/external_resample/speexrate/rate_speexrate.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/drivers/hal/source/sound/component/aw-alsa-utils/resample_speexdsp.o (.text .text.* .rodata .rodata.*)
#endif /* CONFIG_COMPONENTS_AW_ALSA_UTILS */

#ifdef CONFIG_COMPONENTS_AW_AUDIO_SYSTEM
	*build/RTOS_TARGET_PROJECT_PATH/components/common/aw/AudioSystem/libaudiosystem*.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/components/common/aw/AudioSystem/utils/as_test.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/components/common/aw/AudioSystem/audio_hw/audio_hw.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/components/common/aw/AudioSystem/audio_hw/as_pcm.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/components/common/aw/AudioSystem/audio_hw/as_bt.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/components/common/aw/AudioSystem/audio_hw/as_usb.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/components/common/aw/AudioSystem/audio_plugin/softvolume.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/components/common/aw/AudioSystem/audio_plugin/audio_plugin.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/components/common/aw/AudioSystem/audio_plugin/bits_convert.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/components/common/aw/AudioSystem/audio_plugin/channel_maps.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/components/common/aw/AudioSystem/audio_plugin/empty_audio_plugin.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/components/common/aw/AudioSystem/audio_plugin/resample/resample.o (.text .text.* .rodata .rodata.*)
	*build/RTOS_TARGET_PROJECT_PATH/components/common/aw/AudioSystem/audio_plugin/resample/speexrate/resample_speexdsp.o (.text .text.* .rodata .rodata.*)
#endif /* CONFIG_COMPONENTS_AW_AUDIO_SYSTEM */
